const mongoose = require("mongoose");
const mongooseTimestamp = require("mongoose-timestamp");

const employeeMasterSchema = new mongoose.Schema({
  ECODE: { type: String, index: true },
  EMPNO: { type: String, index: true },
  ENAME: String,
  PADR1: String,
  PADR2: String,
  PADR3: String,
  PADR4: String,
  EOFFICE: String,
  PPHONE: String,
  DSGCODE: String,
  EDESIGN: String,
  PASSWORD: { type: String, default: "12345" },
  GRADE: String,
  QUAL: String,
  DOJ: Date,
  DOR: Date,
  BRCODE: { type: String, ref: "BranchMaster", required: true, index: true },
  BRNAME: String,
  SHIFTGRP: String,
  DEPT: String,
  DOB: Date,
  EMPTYPE: String,
  EMPPIN: String,
  EMPCATG: String,
  EMPLEVEL: String,
  SEX: String,
  CCCODE: String,
  GRPCODE: String,
  LOCCODE: String,
  STATUS: { type: String, index: true },
  ORIGINALPHOTO: String,
  LOGINPHOTO: String,
  REPMGR: { type: String, ref: "EmployeeMaster" },
  REPMGRNAME: String,
  REPMGRSTATUS: { type: String, default: "NO" },
  APPMGR: { type: String, ref: "EmployeeMaster" },
  APPMGRNAME: String,
  APPMGRSTATUS: { type: String, default: "NO" }, // For Operation
  REVMGR: String,
  LASTLOGIN: Date,
  LASTLOGOUT: Date,
  USERTOKEN: String,
  DEVICEID: String,
  BRSTARTTIME: { type: String, default: "08:30" },
  BRENDTIME: { type: String, default: "17:30" },
  BLOCKSTATUS: { type: Boolean, default: false },
  DEPUTATION_WITHDRAWAL_STATUS: { type: Boolean, default: false },
  DEPU_FROM_DATE: Date,
  DEPU_TO_DATE: Date,
  DEPU_BRANCH: String,
  RESIGN_WITHDRAWAL_STATUS: { type: Boolean, default: false },
  RESIGN_LETTER: String,
  DOR: Date,
  EXIT_WITHDRAWAL_STATUS: { type: Boolean, default: false },
  EXITDATE: Date,
  HOLD_RELEASE_STATUS: { type: Boolean, default: false },
  RESIDENTIAL_TRANSFER_STATUS: { type: Boolean, default: false },
  CREATEDDATE: { type: Date, default: Date.now },
  isHolidayCheckIn: { type: Boolean, default: false },
});

employeeMasterSchema.plugin(mongooseTimestamp);

const EmployeeMaster = mongoose.model("EmployeeMaster", employeeMasterSchema);

module.exports = EmployeeMaster;
