
    const mongoose = require('mongoose');
    const { Schema } = mongoose;
    
    const jlsSermasDtlSchema = new Schema({
      OM_SED_SMNO: String,
  OM_SED_SMDT: Date,
  OM_SED_JOBNO: String,
  OM_SED_SLNO: Number,
  OM_SED_CONTRACTNO: String,
  OM_SED_CONTRACTDT: Date,
  OM_SED_BRCODE: String,
  OM_SED_NAME: String,
  OM_SED_SERTYPE: String,
  OM_SED_SFRDT: Date,
  OM_SED_STODT: Date,
  OM_SED_SROUTE: String,
  OM_SED_VALUE: Number,
  OM_SED_ADDRESS1: String,
  OM_SED_ADDRESS2: String,
  OM_SED_ADDRESS3: String,
  OM_SED_ADDRESS4: String,
  OM_SED_APINCODE: Number,
  OM_SED_INSTADD1: String,
  OM_SED_INSTADD2: String,
  OM_SED_INSTADD3: String,
  OM_SED_LANDMARK: String,
  OM_SED_IPINCODE: Number,
  OM_SED_REQDSER: Number,
  OM_SED_ACTSER: Number,
  OM_SED_REMARKS: String,
  OM_SED_PREPBY: String,
  OM_SED_PREPDT: Date,
  OM_SED_MODBY: String,
  OM_SED_MODDT: Date,
  OM_SED_STATUS: String,
  OM_SED_CONTACTNAME1: String,
  OM_SED_CONTACTNO1: String,
  OM_SED_CONTACTNAME2: String,
  OM_SED_CONTACTNO2: String,
  OM_SED_REMARKS1: String,
  OM_SED_REMARKS2: String,
  OM_SED_FAXNO: String,
  OM_SED_EMAILID: String,
  OM_SED_SERFREQ: String,
  OM_SED_PSMVAL: Number,
  OM_SED_GSMVAL: Number,
  OM_SED_SSMVAL: Number,
  OM_SED_OSERTYPE: String,
  OM_SED_APPRBY: String,
  OM_SED_APPRDT: Date,
  OM_SED_TAXAMT: Number,
  OM_SED_TAXPER: Number,
  OM_SED_PRTFLAG: String,
  OM_SED_CUSORDNO: String,
  OM_SED_CUSORDDT: Date,
  OM_SED_REMINDNO: Number,
  OM_SED_REMINDDT: Date,
  OM_SED_PAYFREQ: String,
  OM_SED_PAYTYPE: String,
  OM_SED_AMENDNO: Number,
  OM_SED_AMENDDT: Date,
  OM_SED_TAXEXEMPT: String,
  OM_SED_BRREMARKS: String,
  OM_SED_CUSCTG: String,
  OM_SED_TAXINCL: String,
  OM_SED_LRCTVCHR: String,
  OM_SED_LRCTDATE: Date,
  OM_SED_OMOLDJOBNO: String,
    });
    module.exports = mongoose.model('OM_SERMAS_DTL', jlsSermasDtlSchema);
    