var mongoose = require('mongoose');
const Schema = mongoose.Schema; 
var timestamps = require('mongoose-timestamp');
const ssales_customer_infoSchema = new mongoose.Schema({    
    JLS_SSCI_JOBNO: String,
    JLS_SSCI_CONTRACTNO: String,
    JLS_SSCI_CUSCODE: String,
    JLS_SSCI_CUSTOMERNAME: String,
    JLS_SSCI_CA_CUSTOMERNAME: String,
    JLS_SSCI_CA_BUILDNAME: String,
    JLS_SSCI_CA_DOOR_BLKNO: String,
    JLS_SSCI_CA_STNAME: String,
    JLS_SSCI_CA_AREA: String,
    JLS_SSCI_CA_LOCATION: String,
    JLS_SSCI_CA_CITY: String,
    JLS_SSCI_CA_STATE: String,
    JLS_SSCI_CA_PIN: Number,
    JLS_SSCI_CA_EMAIL: String,
    JLS_SSCI_CA_MOBILENO: Number,
    JLS_SSCI_CA_PANNO: String,
    JLS_SSCI_CA_TANNO: String,
    JLS_SSCI_PA_BUILDNAME: String,
    JLS_SSCI_PA_DOOR_BLKNO: String,
    JLS_SSCI_PA_STNAME: String,
    JLS_SSCI_PA_AREA: String,
    JLS_SSCI_PA_LOCATION: String,
    JLS_SSCI_PA_CITY: String,
    JLS_SSCI_PA_STATE: String,
    JLS_SSCI_PA_PIN: Number,
    JLS_SSCI_PA_MOBILENO: Number,
    JLS_SSCI_IA_BUILDNAME: String,
    JLS_SSCI_IA_DOOR_BLKNO: String,
    JLS_SSCI_IA_STNAME: String,
    JLS_SSCI_IA_AREA: String,
    JLS_SSCI_IA_LOCATION: String,
    JLS_SSCI_IA_CITY: String,
    JLS_SSCI_IA_STATE: String,
    JLS_SSCI_IA_PIN: Number,
    JLS_SSCI_IA_MOBILENO: Number,
    JLS_SSCI_IA_GSTN_NO: String,
    JLS_SSCI_TECHNAME: String,
    JLS_SSCI_PA_KINDATTN: String,

    JLS_SSPRE_SERV_BRANCH: String,
    JLS_SSPRE_ORD_BRCODE: String,
    JLS_SSPRE_BILL_STCD: String,
    JLS_SSPRE_CUSCODE: String,
    JLS_SSPRE_CUSTOMERNAME: String,
    JLS_SSPRE_CUSTADDRESS: String,
    JLS_SSPRE_PINCODE: Number,
    JLS_SSPRE_VSTATE: String,
    JLS_SSPRE_STATENAME: String,
    JLS_SSPRE_GSTNO: String,
    JLS_SSPRE_INSTADDRESS: String,
    JLS_SSPRE_LANDMARK: String,
    JLS_SSPRE_CUSTPIN: Number,
    JLS_SSPRE_PANNO: String,
    JLS_SSPRE_CONTNAME: String,
    JLS_SSPRE_CONTNO: String,
    JLS_SSPRE_EMAIL: String,
    JLS_SSPRE_TANNO: String,
    JLS_SSCI_CUSTOMER_SIGN: String,
    JLS_SSCI_CUSTOMER_DATE: Date,
    JLS_SSCI_SALES_EXEC_NAME: String,
    JLS_SSCI_SALES_EXEC_SIGN: String,
    JLS_SSCI_SALES_EXEC_DATE: Date,
    JLS_SED_GRP_JOB: String,
    PDF_PATH: String,
    PDF_NAME: String,
    JLS_SS_CA_FLAG: { type: Boolean, default: false },
    JLS_SS_IA_FLAG: { type: Boolean, default: false },
    JLS_SS_PA_FLAG: { type: Boolean, default: false }
});

mongoose.model('ssales_customer_info', ssales_customer_infoSchema);
ssales_customer_infoSchema.plugin(timestamps);
module.exports = mongoose.model('ssales_customer_info');